### ISSUE TITLE
NPM Fails when installing Jsjws with LNK1181 Error

### ISSUE THREAD

**Issue by PB314** [davedoesdev/node-jsjws#8]
Is there any way of installing jsjws on node.js without needing to use NPM.   

Trying to use NPM it  fails on Windows 7 looking for "OpenSSL-Win64"in the root directory so obviously there is a major corruption in the NPM install package.  Apart from that there are pages of of errors which it is just not worth persevering with.

**Comment by davedoesdev** [comment]
@PB314 thanks for the heads up. I'll try to find a Windows machine to try.

**Comment by davedoesdev** [comment]
@PB314 which version of OpenSSL for Windows do you have installed?

**Comment by davedoesdev** [comment]
I tried on Windows 10. With OpenSSL 1.0.2h, `jsjws` installs fine. With OpenSSL 1.1.0 however, it fails to install due to [`ursa`](https://github.com/quartzjer/ursa) failing to install.

The cause is probably due to OpenSSL renaming their libraries from 1.1.0 onwards. See similar issue here: https://github.com/curl/curl/issues/984

Please create an issue at https://github.com/quartzjer/ursa/issues. I suspect this will be an issue on non-Windows platforms as they upgrade to OpenSSL 1.1.0 too.

**Comment by davedoesdev** [comment]
It seems Node from 6.3.0 onwards exports the OpenSSL symbols on Windows https://github.com/nodejs/node/commit/15a32dd

That would make ursa's job much easier on Windows.

**Comment by davedoesdev** [comment]
I've made a PR for ursa (https://github.com/quartzjer/ursa/pull/149) which would eliminate the need for a separate OpenSSL install on Windows, at the cost of making ursa work only on Node 6.3.0 upwards on Windows.

**Comment by davedoesdev** [comment]
Update: I'm working to remove `ursa` from my dependencies now that Node's builtin `crypto` module has support for signing with certs and RSAPSS.

**Comment by davedoesdev** [comment]
@PB314 node-jsjws version 3 installs on Windows because I removed the dependency on ursa. It does however require Node version 8.
